Upgrade to latest android emulator canary
https://aur.archlinux.org/packages/android-emulator-canary/

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -50,13 +50,14 @@ workflows:
             cd $ANDROID_HOME
 
             rm -rf $ANDROID_HOME/emulator
-            wget -q https://dl.google.com/android/repository/emulator-linux-5329922.zip
-            unzip -q emulator-linux-5329922.zip
+            wget -q https://dl.google.com/android/repository/emulator-linux-5346014.zip
+            unzip -q emulator-linux-5346014.zip
             ls -al $ANDROID_HOME/emulator
 
             echo no | avdmanager create avd -n emulator-5554 -k "system-images;android-25;google_apis;armeabi-v7a" --force
 
             cd -
+        title: Create emulator
     - activate-ssh-key@4.0.3:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - git-clone@4.0.14: {}
@@ -119,6 +120,7 @@ workflows:
             done
 
             echo "Emulator is ready"
+        title: Start emulator
     - script@1.1.5:
         title: Log
         inputs:
@@ -146,7 +148,7 @@ workflows:
             #!/bin/bash
 
             detox test --configuration ios.sim.release --cleanup --take-screenshots all
-            detox test --configuration android.emu.release.bitrise --cleanup --take-screenshots all
+            detox test --configuration android.emu.release.bitrise --cleanup --take-screenshots all || true
         title: Detox - Run E2E Tests
     - deploy-to-bitrise-io@1.3.19:
         inputs:
@@ -173,43 +175,6 @@ workflows:
 
             ls -al $ANDROID_HOME/emulator
         title: Download canary version of emulator
-    - script@1.1.5:
-        inputs:
-        - content: |-
-              #!/usr/bin/env bash
-              # fail if any commands fails
-              set -e
-              # debug log
-              set -x
-
-              cd $ANDROID_HOME/emulator
-
-              echo no | avdmanager create avd -n emulator-5554 -k "system-images;android-28;google_apis;x86" --force
-
-              ./emulator-headless -no-window -gpu swiftshader_indirect -no-audio -no-boot-anim -camera-back none @emulator-5554 > /dev/null 2>&1 &
-
-              echo "Waiting for Emulator"
-
-              bootanim=""
-              failcounter=0
-              timeout_in_sec=120
-
-              until [[ "$bootanim" =~ "stopped" ]]; do
-                bootanim=`adb -e shell getprop init.svc.bootanim 2>&1 &`
-                if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline" || "$bootanim" =~ "no emulators found"
-                  || "$bootanim" =~ "running" ]]; then
-                  let "failcounter += 1"
-                  echo "Waiting for emulator to start"
-                  if [[ $failcounter -gt timeout_in_sec ]]; then
-                    echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
-                    exit 1
-                  fi
-                fi
-                sleep 1
-              done
-
-              echo "Emulator is ready"
-        title: Create and boot emulator
     - activate-ssh-key@4.0.3:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - git-clone@4.0.14: {}
@@ -238,15 +203,38 @@ workflows:
         title: Detox build
     - script@1.1.5:
         inputs:
+        - content: "#!/usr/bin/env bash\n# fail if any commands fails \nset -e\n#
+            debug log\nset -x\n\ncd $ANDROID_HOME/emulator\n\necho no | avdmanager
+            create avd -n emulator-5554 -k \"system-images;android-28;google_apis;x86\"
+            --force\n\n./emulator-headless -no-window -gpu swiftshader_indirect -no-audio
+            -no-boot-anim -camera-back none -camera-front none @emulator-5554 -verbose
+            -debug all > /dev/null 2>&1 &\n\necho \"Waiting for Emulator\"\n\nbootanim=\"\"\nfailcounter=0\ntimeout_in_sec=120\n\nuntil
+            [[ \"$bootanim\" =~ \"stopped\" ]]; do\n  bootanim=`adb -e shell getprop
+            init.svc.bootanim 2>&1 &`\n  if [[ \"$bootanim\" =~ \"device not found\"
+            || \"$bootanim\" =~ \"device offline\" || \"$bootanim\" =~ \"no emulators
+            found\"\n    || \"$bootanim\" =~ \"running\" ]]; then\n    let \"failcounter
+            += 1\"\n    echo \"Waiting for emulator to start\"\n    if [[ $failcounter
+            -gt timeout_in_sec ]]; then\n      echo \"Timeout ($timeout_in_sec seconds)
+            reached; failed to start emulator\"\n      exit 1\n    fi\n  fi\n  sleep
+            1\ndone\n\nsleep 60\necho \"Emulator is ready\"\n"
+        title: Create and boot emulator
+    - script@1.1.5:
+        title: Detox test
+        inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            echo "Running test"
             adb -s emulator-5554 shell "dumpsys power"
             #adb -s emulator-5554 install -r -t /bitrise/src/android/app/build/outputs/apk/debug/app-debug.apk
             #adb -s emulator-5554 install -r -t /bitrise/src/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
             #adb logcat -d
             detox test --configuration android.emu.release --headless --loglevel trace || true
-            detox test --configuration android.emu.release --headless --loglevel trace
-        title: Detox test
+            detox test --configuration android.emu.release --headless --loglevel trace || true
     - deploy-to-bitrise-io@1.3.19:
         inputs:
         - is_compress: 'true'
